### ISSUE TITLE
provider throwing internal server error

### ISSUE THREAD

**Issue by reetasingh** [salesforce/terraform-provider-policyguru#9]
```
make: *** [terraform-demo] Error 1
reetasingh-ltm8:terraform-provider-policyguru reetasingh$ make clean
make: *** No rule to make target `clean'.  Stop.
reetasingh-ltm8:terraform-provider-policyguru reetasingh$ make terraform-demo
go build -o terraform-provider-policyguru
mv terraform-provider-policyguru ~/.terraform.d/plugins
cd examples && terraform init && terraform apply

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/aws v3.21.0
- Using previously-installed salesforce/policyguru v2.0.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.policyguru_document.example: Refreshing state...

Error: status: 500, body: {"message":"Internal Server Error"}


make: *** [terraform-demo] Error 1
reetasingh-ltm8:terraform-provider-policyguru reetasingh$ 

```

**Comment by reetasingh** [comment]
this is a problem on API side. we are working on fix for it in the API repo

**Comment by reetasingh** [comment]
this issue is resolved on API side repo

**Comment by reetasingh** [comment]
terraform-provider is working now

**Comment by reetasingh** [comment]
```
Terraform will perform the following actions:

  # data.policyguru_document.example will be read during apply
  # (config refers to values not yet known)
 <= data "policyguru_document" "example"  {
      ~ id   = "1609789420" -> "1609789421"
        json = jsonencode(
            {
                Statement = [
                    {
                        Action   = [
                            "s3:GetAccelerateConfiguration",
                            "s3:GetAnalyticsConfiguration",
                            "s3:GetBucketAcl",
                            "s3:GetBucketCORS",
                            "s3:GetBucketLocation",
                            "s3:GetBucketLogging",
                            "s3:GetBucketNotification",
                            "s3:GetBucketObjectLockConfiguration",
                            "s3:GetBucketOwnershipControls",
                            "s3:GetBucketPolicy",
                            "s3:GetBucketPolicyStatus",
                            "s3:GetBucketPublicAccessBlock",
                            "s3:GetBucketRequestPayment",
                            "s3:GetBucketTagging",
                            "s3:GetBucketVersioning",
                            "s3:GetBucketWebsite",
                            "s3:GetEncryptionConfiguration",
                            "s3:GetInventoryConfiguration",
                            "s3:GetLifecycleConfiguration",
                            "s3:GetMetricsConfiguration",
                            "s3:GetReplicationConfiguration",
                        ]
                        Effect   = "Allow"
                        Resource = [
                            "arn:aws:s3:::mybucket",
                        ]
                        Sid      = "S3ReadBucket"
                    },
                ]
                Version   = "2012-10-17"
            }
        )

        actions_for_resources_at_access_level {
            list                   = []
            permissions_management = []
            read                   = [
                "arn:aws:s3:::mybucket",
            ]
            tagging                = []
            write                  = []
        }
    }

  # aws_iam_policy.policy will be created
  + resource "aws_iam_policy" "policy" {
      + arn         = (known after apply)
      + description = "this uses policyguru document"
      + id          = (known after apply)
      + name        = "sample2"
      + path        = "/"
      + policy      = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "s3:GetAccelerateConfiguration",
                          + "s3:GetAnalyticsConfiguration",
                          + "s3:GetBucketAcl",
                          + "s3:GetBucketCORS",
                          + "s3:GetBucketLocation",
                          + "s3:GetBucketLogging",
                          + "s3:GetBucketNotification",
                          + "s3:GetBucketObjectLockConfiguration",
                          + "s3:GetBucketOwnershipControls",
                          + "s3:GetBucketPolicy",
                          + "s3:GetBucketPolicyStatus",
                          + "s3:GetBucketPublicAccessBlock",
                          + "s3:GetBucketRequestPayment",
                          + "s3:GetBucketTagging",
                          + "s3:GetBucketVersioning",
                          + "s3:GetBucketWebsite",
                          + "s3:GetEncryptionConfiguration",
                          + "s3:GetInventoryConfiguration",
                          + "s3:GetLifecycleConfiguration",
                          + "s3:GetMetricsConfiguration",
                          + "s3:GetReplicationConfiguration",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::mybucket",
                        ]
                      + Sid      = "S3ReadBucket"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

```

**Comment by jelledv** [comment]
I am still getting "Error: status: 500, body: {"message":"Internal Server Error"}" after executing terraform plan

**Comment by rhnasc** [comment]
@reetasingh I'm still receiving that error... is this provider ready for production?

Also, are you guys planning on open-sourcing the REST API? This would be make the provider more interesting for adoption, security-wise
